on:
#  to enable running from GitHub UI
  workflow_dispatch:
    branches:
      - master

  push:
    branches:
      - master

name: Analyze dart
jobs:
  build:
    name: 3rd dart analyzer + unit with coverage + coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'

      - name: Get dependecy
        run: flutter pub get

      - name: Analyze code
#   with all info level logs the action will fail
#        run: dart analyze --fatal-infos
        run: dart analyze

      - name: Run unit & widget tests
        run: flutter test --coverage


