on:
  push:
    branches:
      - master

name: Analyze dart
jobs:
  build:
    name: 1st dart analyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'

      - name: Install dependecy
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze